branch-defaults:
  master:
    environment: NodeWebApp-env
environment-defaults:
  NodeDevApp-env:
    branch: null
    repository: null
global:
  application_name: NodeWebApp
  default_ec2_keyname: i-0e944597fd7be9b9a
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Multi-container Docker running on 64bit Amazon Linux/2.20.2
  default_region: us-east-2c
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: git
  workspace_type: Application