version: 2.1
orbs:
  docker: circleci/docker@1.0.1
jobs:
  test:
    working_directory: ~/app
    docker: 
      - image: circleci/node:latest    
    steps:
      - checkout
      - run: 'sudo npm install -g npm@latest'
          # name: Update npm
          # command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependecy-cache-{{ checksum "package-lock.json" }}
      - run: 'npm run initial' 
        # name: Install npm dependencies
        # command: 'npm run initial' 
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      # - run:
      #   name: Run test
      #   command: 'npm run start'
  docker-deploy-image:
    working_directory: ~/app
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - docker/push:
          image: dillonkyle/node-dev-app
      # - run: | 
      #     docker image build -t dillonkyle/node-dev-app:latest .
      #     docker login -u $DOCKER_USER -p $DOCKER_PASS
      #     docker push dillonkyle/node-dev-app
  deploy-aws:
    working_directory: ~/app
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: 
          name: Installing deployment dependencies
          working_directory: /
          command: 'sudo pip install awsebcli --upgrade'
      - run: 
          name: Deploying application to Elastic Beanstalk
          command: eb deploy
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - docker-deploy-image:
          context: node-dev-app
          requires:
            - test
      - deploy-aws:
          requires:
            - docker-deploy-image