version: 2
# orbs:
#   docker: circleci/docker@1.0.1
jobs:
  build:
    working_directory: ~/app
    docker: 
      - image: circleci/node:latest    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          command: docker build -t dillonkyle/node-dev-app:latest .
      - run:
          name: Docker Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker Push
          command: docker push dillonkyle/node-dev-app:latest
  deploy-aws:
    working_directory: ~/app
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: 
          name: Installing AWSCLI
          command: 'sudo pip install awsebcli --upgrade'
      - run: 
          name: Create AWS credentials
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Deploy to EB if branch is Master
          command: |
            eb use NodeDevApp-env --profile eb-cli
            eb deploy -v --staged --profile eb-cli
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-aws:
        requires:
          - build
