const ACCOUNT = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
    FETCH_AUTHENTICATED_SUCCESS: 'FETCH_AUTHENTICATED_SUCCESS'
};

const ACCOUNT_INFO ={
    FETCH: 'ACCOUNT_INFO_FETCH',
    FETCH_ERROR: 'ACCOUNT_INFO_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_INFO_SUCCESS'
};

const ACCOUNT_CREATION ={
    FETCH: 'ACCOUNT_CREATION_FETCH',
    FETCH_ERROR: 'ACCOUNT_CREATION_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_CREATION_SUCCESS'
};

export { ACCOUNT_INFO, ACCOUNT, ACCOUNT_CREATION };